import { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import {
  getEffectiveVisibility,
  getInheritanceChain,
  upsertVisibilityRule,
  createOverride,
  deleteVisibilityRule,
  listVisibilityRules,
  getVisibilityRule,
  ensureTenantDefaults,
  disableInheritance,
  getDefaultConfig,
  type StudVisibilityConfig,
} from "../services/stud-visibility-service.js";

// Type will be generated by Prisma after migration
type StudVisibilityLevel = "TENANT" | "PROGRAM" | "PARTICIPANT";

export default async function studVisibilityRoutes(app: FastifyInstance) {
  /**
   * GET /api/v1/stud-visibility/effective
   * Get effective (resolved) visibility config for a level
   */
  app.get("/stud-visibility/effective", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const query = req.query as { level?: string; levelId?: string };
      const { level, levelId } = query;
      const tenantId = (req as any).tenantId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      if (!level || !levelId) {
        return reply.code(400).send({ error: "Missing required parameters: level, levelId" });
      }

      const validLevels: StudVisibilityLevel[] = ["TENANT", "PROGRAM", "PARTICIPANT"];
      if (!validLevels.includes(level as StudVisibilityLevel)) {
        return reply.code(400).send({
          error: "Invalid level. Must be: TENANT, PROGRAM, or PARTICIPANT",
        });
      }

      // Ensure tenant has default rules
      await ensureTenantDefaults(tenantId);

      const effective = await getEffectiveVisibility(
        tenantId,
        level as StudVisibilityLevel,
        levelId
      );

      return reply.send({ effective });
    } catch (error) {
      req.log.error({ err: error }, "Error fetching effective visibility");
      return reply.code(500).send({ error: "Failed to fetch effective visibility" });
    }
  });

  /**
   * GET /api/v1/stud-visibility/rules
   * List visibility rules for a tenant
   */
  app.get("/stud-visibility/rules", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const query = req.query as { level?: string; levelId?: string };
      const { level, levelId } = query;
      const tenantId = (req as any).tenantId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      const rules = await listVisibilityRules(tenantId, {
        level: level as StudVisibilityLevel | undefined,
        levelId,
      });

      return reply.send({ rules });
    } catch (error) {
      req.log.error({ err: error }, "Error fetching visibility rules");
      return reply.code(500).send({ error: "Failed to fetch visibility rules" });
    }
  });

  /**
   * GET /api/v1/stud-visibility/rules/:id
   * Get a specific rule by ID
   */
  app.get("/stud-visibility/rules/:id", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const params = req.params as { id: string };
      const { id } = params;
      const tenantId = (req as any).tenantId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      const rule = await getVisibilityRule(tenantId, parseInt(id, 10));

      if (!rule) {
        return reply.code(404).send({ error: "Rule not found" });
      }

      return reply.send({ rule });
    } catch (error) {
      req.log.error({ err: error }, "Error fetching visibility rule");
      return reply.code(500).send({ error: "Failed to fetch visibility rule" });
    }
  });

  /**
   * POST /api/v1/stud-visibility/rules
   * Create or update a visibility rule at a level
   */
  app.post("/stud-visibility/rules", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const body = req.body as {
        level: string;
        levelId: string;
        config: Partial<StudVisibilityConfig>;
        enabled?: boolean;
        inheritsFromId?: number;
      };
      const tenantId = (req as any).tenantId;
      const userId = (req as any).userId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      const { level, levelId, config, enabled, inheritsFromId } = body;

      if (!level || !levelId || !config) {
        return reply.code(400).send({
          error: "Missing required fields: level, levelId, config",
        });
      }

      const validLevels: StudVisibilityLevel[] = ["TENANT", "PROGRAM", "PARTICIPANT"];
      if (!validLevels.includes(level as StudVisibilityLevel)) {
        return reply.code(400).send({
          error: "Invalid level. Must be: TENANT, PROGRAM, or PARTICIPANT",
        });
      }

      const rule = await upsertVisibilityRule(
        tenantId,
        level as StudVisibilityLevel,
        levelId,
        config,
        {
          enabled,
          inheritsFromId,
          updatedBy: userId,
        }
      );

      return reply.code(201).send({ rule });
    } catch (error) {
      req.log.error({ err: error }, "Error creating/updating visibility rule");
      return reply.code(500).send({ error: "Failed to create/update visibility rule" });
    }
  });

  /**
   * POST /api/v1/stud-visibility/rules/:id/override
   * Create an override at a child level
   */
  app.post("/stud-visibility/rules/:id/override", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const params = req.params as { id: string };
      const body = req.body as {
        level: string;
        levelId: string;
        config: Partial<StudVisibilityConfig>;
      };
      const tenantId = (req as any).tenantId;
      const userId = (req as any).userId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      const { level, levelId, config } = body;

      if (!level || !levelId || !config) {
        return reply.code(400).send({
          error: "Missing required fields: level, levelId, config",
        });
      }

      const validLevels: StudVisibilityLevel[] = ["PROGRAM", "PARTICIPANT"];
      if (!validLevels.includes(level as StudVisibilityLevel)) {
        return reply.code(400).send({
          error: "Invalid level for override. Must be: PROGRAM or PARTICIPANT",
        });
      }

      const override = await createOverride(
        tenantId,
        level as StudVisibilityLevel,
        levelId,
        config,
        userId
      );

      return reply.code(201).send({ override });
    } catch (error) {
      req.log.error({ err: error }, "Error creating visibility override");
      return reply.code(500).send({ error: "Failed to create visibility override" });
    }
  });

  /**
   * DELETE /api/v1/stud-visibility/rules/:id
   * Delete a rule (reverts to parent inheritance)
   */
  app.delete("/stud-visibility/rules/:id", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const params = req.params as { id: string };
      const tenantId = (req as any).tenantId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      // Get the rule first to get level/levelId
      const rule = await getVisibilityRule(tenantId, parseInt(params.id, 10));

      if (!rule) {
        return reply.code(404).send({ error: "Rule not found" });
      }

      // Don't allow deleting tenant-level rules
      if (rule.level === "TENANT") {
        return reply.code(400).send({
          error: "Cannot delete tenant-level rules. Reset to defaults instead.",
        });
      }

      const result = await deleteVisibilityRule(tenantId, rule.level, rule.levelId);

      return reply.send(result);
    } catch (error) {
      req.log.error({ err: error }, "Error deleting visibility rule");
      return reply.code(500).send({ error: "Failed to delete visibility rule" });
    }
  });

  /**
   * GET /api/v1/stud-visibility/chain
   * Get inheritance chain for debugging/UI
   */
  app.get("/stud-visibility/chain", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const query = req.query as { level?: string; levelId?: string };
      const { level, levelId } = query;
      const tenantId = (req as any).tenantId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      if (!level || !levelId) {
        return reply.code(400).send({ error: "Missing required parameters: level, levelId" });
      }

      const validLevels: StudVisibilityLevel[] = ["TENANT", "PROGRAM", "PARTICIPANT"];
      if (!validLevels.includes(level as StudVisibilityLevel)) {
        return reply.code(400).send({
          error: "Invalid level. Must be: TENANT, PROGRAM, or PARTICIPANT",
        });
      }

      const chain = await getInheritanceChain(tenantId, level as StudVisibilityLevel, levelId);

      return reply.send({ chain });
    } catch (error) {
      req.log.error({ err: error }, "Error fetching inheritance chain");
      return reply.code(500).send({ error: "Failed to fetch inheritance chain" });
    }
  });

  /**
   * POST /api/v1/stud-visibility/disable-inheritance
   * Stop inheriting from parent and create local copy
   */
  app.post("/stud-visibility/disable-inheritance", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const body = req.body as {
        currentLevel: string;
        currentLevelId: string;
      };
      const tenantId = (req as any).tenantId;
      const userId = (req as any).userId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      const { currentLevel, currentLevelId } = body;

      if (!currentLevel || !currentLevelId) {
        return reply.code(400).send({
          error: "Missing required fields: currentLevel, currentLevelId",
        });
      }

      const validLevels: StudVisibilityLevel[] = ["PROGRAM", "PARTICIPANT"];
      if (!validLevels.includes(currentLevel as StudVisibilityLevel)) {
        return reply.code(400).send({
          error: "Invalid level. Must be: PROGRAM or PARTICIPANT",
        });
      }

      const rule = await disableInheritance(
        tenantId,
        currentLevel as StudVisibilityLevel,
        currentLevelId,
        userId
      );

      return reply.send({ success: true, rule });
    } catch (error) {
      req.log.error({ err: error }, "Error disabling inheritance");
      return reply.code(500).send({ error: "Failed to disable inheritance" });
    }
  });

  /**
   * GET /api/v1/stud-visibility/defaults
   * Get the default visibility config (for reference/reset)
   */
  app.get("/stud-visibility/defaults", async (req: FastifyRequest, reply: FastifyReply) => {
    try {
      const tenantId = (req as any).tenantId;

      if (!tenantId) {
        return reply.code(401).send({ error: "Not authenticated" });
      }

      const defaults = getDefaultConfig();

      return reply.send({ defaults });
    } catch (error) {
      req.log.error({ err: error }, "Error fetching default config");
      return reply.code(500).send({ error: "Failed to fetch default config" });
    }
  });
}
