-- CreateEnum
CREATE TYPE "public"."BuyerEmailTemplateCategory" AS ENUM ('GENERAL', 'INITIAL_CONTACT', 'FOLLOW_UP', 'VIEWING', 'NEGOTIATION', 'CLOSING');

-- CreateEnum
CREATE TYPE "public"."BuyerTaskType" AS ENUM ('FOLLOW_UP', 'CALL', 'EMAIL', 'SCHEDULE_VIEWING', 'SEND_INFO', 'VET_CHECK', 'CONTRACT', 'PAYMENT', 'OTHER');

-- CreateEnum
CREATE TYPE "public"."BuyerTaskPriority" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'URGENT');

-- CreateEnum
CREATE TYPE "public"."BuyerTaskStatus" AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'DEFERRED');

-- CreateTable
CREATE TABLE "public"."BuyerEmailTemplate" (
    "id" SERIAL NOT NULL,
    "tenantId" INTEGER NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "subject" VARCHAR(255) NOT NULL,
    "bodyHtml" TEXT NOT NULL,
    "bodyText" TEXT NOT NULL,
    "category" "public"."BuyerEmailTemplateCategory" NOT NULL DEFAULT 'GENERAL',
    "useCount" INTEGER NOT NULL DEFAULT 0,
    "lastUsedAt" TIMESTAMP(3),
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BuyerEmailTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."BuyerTask" (
    "id" SERIAL NOT NULL,
    "tenantId" INTEGER NOT NULL,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "taskType" "public"."BuyerTaskType" NOT NULL DEFAULT 'FOLLOW_UP',
    "priority" "public"."BuyerTaskPriority" NOT NULL DEFAULT 'MEDIUM',
    "status" "public"."BuyerTaskStatus" NOT NULL DEFAULT 'PENDING',
    "dueAt" TIMESTAMP(3),
    "reminderAt" TIMESTAMP(3),
    "buyerId" INTEGER,
    "dealId" INTEGER,
    "animalId" INTEGER,
    "assignedToUserId" TEXT,
    "completedAt" TIMESTAMP(3),
    "completedById" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "automationRule" VARCHAR(100),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "BuyerTask_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BuyerEmailTemplate_tenantId_idx" ON "public"."BuyerEmailTemplate"("tenantId");

-- CreateIndex
CREATE INDEX "BuyerEmailTemplate_tenantId_category_idx" ON "public"."BuyerEmailTemplate"("tenantId", "category");

-- CreateIndex
CREATE INDEX "BuyerEmailTemplate_tenantId_isActive_idx" ON "public"."BuyerEmailTemplate"("tenantId", "isActive");

-- CreateIndex
CREATE INDEX "BuyerTask_tenantId_idx" ON "public"."BuyerTask"("tenantId");

-- CreateIndex
CREATE INDEX "BuyerTask_tenantId_status_idx" ON "public"."BuyerTask"("tenantId", "status");

-- CreateIndex
CREATE INDEX "BuyerTask_tenantId_dueAt_idx" ON "public"."BuyerTask"("tenantId", "dueAt");

-- CreateIndex
CREATE INDEX "BuyerTask_buyerId_idx" ON "public"."BuyerTask"("buyerId");

-- CreateIndex
CREATE INDEX "BuyerTask_dealId_idx" ON "public"."BuyerTask"("dealId");

-- CreateIndex
CREATE INDEX "BuyerTask_assignedToUserId_idx" ON "public"."BuyerTask"("assignedToUserId");

-- CreateIndex
CREATE INDEX "BuyerTask_tenantId_status_dueAt_idx" ON "public"."BuyerTask"("tenantId", "status", "dueAt");

-- AddForeignKey
ALTER TABLE "public"."BuyerEmailTemplate" ADD CONSTRAINT "BuyerEmailTemplate_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "public"."Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BuyerTask" ADD CONSTRAINT "BuyerTask_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "public"."Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BuyerTask" ADD CONSTRAINT "BuyerTask_buyerId_fkey" FOREIGN KEY ("buyerId") REFERENCES "public"."Buyer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BuyerTask" ADD CONSTRAINT "BuyerTask_dealId_fkey" FOREIGN KEY ("dealId") REFERENCES "public"."Deal"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BuyerTask" ADD CONSTRAINT "BuyerTask_animalId_fkey" FOREIGN KEY ("animalId") REFERENCES "public"."Animal"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BuyerTask" ADD CONSTRAINT "BuyerTask_assignedToUserId_fkey" FOREIGN KEY ("assignedToUserId") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BuyerTask" ADD CONSTRAINT "BuyerTask_completedById_fkey" FOREIGN KEY ("completedById") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
